package com.unityrealms.server.modelengine.model.skeleton.bone

import com.google.gson.Gson
import com.magmaguy.freeminecraftmodels.dataconverter.LocatorBlueprint
import com.unityrealms.server.modelengine.model.resourcepack.ResourcePackConverter
import com.unityrealms.server.modelengine.logger.Logger
import com.unityrealms.server.modelengine.model.ParsedTexture
import com.unityrealms.server.modelengine.model.skeleton.bone.cube.CubeBlueprint
import com.unityrealms.server.modelengine.model.skeleton.SkeletonBlueprint
import org.joml.Vector3f

import java.io.File
import java.nio.charset.StandardCharsets

import kotlin.math.abs

class BoneBlueprint {

  private val uniqueIdentifier: String?

  private var file: File? = null


  private val originalModelName: String?

  private val modelName: String? = null


  private val originalBoneName: String

  private val boneName: String


  private var boneBlueprintModelCenter: Vector3f = Vector3f()

  private var boneBlueprintOriginalRotation: Vector3f = Vector3f()

  private var boneBlueprintModelPivot: Vector3f? = null


  private var parentBoneBlueprint: BoneBlueprint? = null

  private var metadataBoneBlueprint: BoneBlueprint? = null


  private val cubeBlueprintChildren: MutableList<CubeBlueprint> = ArrayList()

  private val boneBlueprintChildren: MutableList<BoneBlueprint?> = ArrayList<BoneBlueprint?>()


  private var isDisplayModel = true

  private var isHead = false

  private var isMountPoint = false

  private var isNameTag = false

  /**
   * Constructs a root bone for a model, which is used to hold the cubes and child bones.
   *
   * @param modelName The name of the model.
   * @param skeletonBlueprint The skeleton blueprint.
   * @param parentBoneBlueprint The parent bone blueprint.
   */
  @Deprecated("No real deprecation, just remember to change 'freemiencraftmodels' to 'model-engine'")
  constructor(modelName: String, skeletonBlueprint: SkeletonBlueprint, parentBoneBlueprint: BoneBlueprint?) {
    this.uniqueIdentifier = null

    this.originalModelName = modelName

    this.originalBoneName = "freeminecraftmodels_autogenerated_root"
    this.boneName = "freeminecraftmodels:" + modelName + "/" + ResourcePackConverter.convert(this.originalBoneName)

    this.boneBlueprintOriginalRotation = Vector3f()
    this.boneBlueprintModelPivot = Vector3f()

    this.parentBoneBlueprint = parentBoneBlueprint

    skeletonBlueprint.boneMap[this.originalBoneName] = this
  }

  /**
   * Constructs a bone blueprint for a model, which is used to hold the cubes and child bones.
   *
   * @param modelName The name of the model.
   * @param skeletonBlueprint The skeleton blueprint.
   * @param parentBoneBlueprint The parent bone blueprint.
   * @param boneMap The map of bones in the model.
   */
  @Deprecated("No real deprecation, just remember to change 'freemiencraftmodels' to 'model-engine'")
  constructor(
    modelName: String,
    skeletonBlueprint: SkeletonBlueprint,
    parentBoneBlueprint: BoneBlueprint?,
    boneMap: MutableMap<String?, Any?>
  ) {
    this.uniqueIdentifier = null

    this.originalModelName = modelName

    this.originalBoneName = "fmm_nametag_bone_" + boneMap["name"]
    this.boneName = "freeminecraftmodels:" + modelName + "/" + ResourcePackConverter.convert(this.originalBoneName)

    this.parentBoneBlueprint = parentBoneBlueprint

    this.isNameTag = true

    skeletonBlueprint.boneMap[this.originalBoneName] = this

    this.processBoneMap(boneMap)
  }

  /**
   * Constructs a bone blueprint for a model, which is used to hold the cubes and child bones.
   *
   * @param modelName The name of the model.
   * @param skeletonBlueprint The skeleton blueprint.
   * @param parentBoneBlueprint The parent bone blueprint.
   * @param resolutionHeight The resolution height of the model.
   * @param resolutionWidth The resolution width of the model.
   * @param parsedTextureList The list of parsed textures in the model.
   * @param textureReferenceMap The map of texture references in the model.
   * @param boneMap The map of bones in the model.
   * @param cubeMap The map of cubes in the model.
   * @param locatorMap The map of locators in the model.
   * @param nullObjectMap The map of null objects in the model.
   */
  @Deprecated("No real deprecation, just remember to change 'freemiencraftmodels' to 'model-engine'")
  constructor(
    modelName: String,
    skeletonBlueprint: SkeletonBlueprint,
    parentBoneBlueprint: BoneBlueprint?,
    resolutionHeight: Double,
    resolutionWidth: Double,
    parsedTextureList: MutableList<ParsedTexture?>?,
    textureReferenceMap: MutableMap<String?, MutableMap<String?, Any?>?>,
    boneMap: MutableMap<String?, Any?>,
    cubeMap: HashMap<String?, Any?>,
    locatorMap: HashMap<String?, MutableMap<String?, Any?>>,
    nullObjectMap: HashMap<String?, MutableMap<String?, Any?>>
  ) {
    this.uniqueIdentifier = boneMap["uuid"] as String?

    this.originalModelName = modelName

    this.originalBoneName = boneMap["name"] as String
    this.boneName = "freeminecraftmodels:" + modelName + "/" + ResourcePackConverter.convert(this.originalBoneName)

    this.parentBoneBlueprint = parentBoneBlueprint

    if (this.originalBoneName.startsWith("tag_")) {
      this.metadataBoneBlueprint = BoneBlueprint(modelName, skeletonBlueprint, parentBoneBlueprint, boneMap)
    }

    if (this.originalBoneName.startsWith("b_") || this.originalBoneName.equals("hitbox", ignoreCase = true)) {
      this.isDisplayModel = false
    }

    if (this.originalBoneName.startsWith("h_")) {
      this.isHead = true
    }

    if (this.originalBoneName.startsWith("mount_")) {
      this.isMountPoint = true
    }

    skeletonBlueprint.boneMap[this.originalBoneName] = this

    if (this.uniqueIdentifier != null) {
      skeletonBlueprint.boneByUniqueIdentifierMap[this.uniqueIdentifier] = this
    }

    this.processChildren(
      modelName,
      skeletonBlueprint,
      resolutionHeight,
      resolutionWidth,
      parsedTextureList,
      textureReferenceMap,
      boneMap,
      cubeMap,
      locatorMap,
      nullObjectMap
    )

    this.adjustCubePosition()

    this.processBoneMap(boneMap)

    this.generateAndWriteCubes(ResourcePackConverter.convert(this.originalBoneName), textureReferenceMap, modelName)
  }

  fun getBlueprintOriginalBoneRotation(): Vector3f {
    return Vector3f(boneBlueprintOriginalRotation)
  }

  fun isDisplayModel(): Boolean {
    return isDisplayModel && (modelName != null || isNameTag)
  }

  val modelCenter: Vector3f
    //move to real space
    get() {
      val rpToBlocks = 1f / 16f
      val unscale: Float = 1f / ARMOR_STAND_HEAD_SIZE_MULTIPLIER
      return Vector3f(boneBlueprintModelCenter).mul(rpToBlocks * unscale)
    }

  /**
   * Gets the pivot point for the bone blueprint model, which is used for rotation and positioning.
   *
   * @return The pivot point for the bone blueprint model.
   */
  fun getBoneBlueprintModelPivot(): Vector3f {
    return Vector3f(this.boneBlueprintModelPivot)
  }


  /**
   * Adjusts the cubes to be centered around the origin of the model.
   */
  private fun adjustCubePosition() {
    if (this.cubeBlueprintChildren.isEmpty()) {
      return
    }

    var lowestX: Float? = null
    var lowestY: Float? = null
    var lowestZ: Float? = null

    var highestX: Float? = null
    var highestY: Float? = null
    var highestZ: Float? = null

    for (cubeBlueprint in cubeBlueprintChildren) {
      if (lowestX == null || cubeBlueprint.from.get(0) < lowestX) lowestX = cubeBlueprint.from.get(0)
      if (lowestY == null || cubeBlueprint.from.get(1) < lowestY) lowestY = cubeBlueprint.from.get(1)
      if (lowestZ == null || cubeBlueprint.from.get(2) < lowestZ) lowestZ = cubeBlueprint.from.get(2)

      if (highestX == null || cubeBlueprint.to.get(0) > highestX) highestX = cubeBlueprint.to.get(0)
      if (highestY == null || cubeBlueprint.to.get(1) > highestY) highestY = cubeBlueprint.to.get(1)
      if (highestZ == null || cubeBlueprint.to.get(2) > highestZ) highestZ = cubeBlueprint.to.get(2)
    }

    val sizeX = abs(highestX!! - lowestX!!)
    val sizeY = abs(highestY!! - lowestY!!)
    val sizeZ = abs(highestZ!! - lowestZ!!)

    if (sizeX > 48 * MODEL_SCALE || sizeY > 48 * MODEL_SCALE || sizeZ > 48 * MODEL_SCALE) {
      Logger.warn("Model '${this.originalModelName}' has a bone blueprint or set of cubes which exceeds the maximum size.")
    }

    val newLowestX = 8 - sizeX / 2.0F
    val newLowestY = 8 - sizeY / 2.0F
    val newLowestZ = 8 - sizeZ / 2.0F

    val offsetX = lowestX - newLowestX
    val offsetY = lowestY - newLowestY
    val offsetZ = lowestZ - newLowestZ

    val cubeOffset = Vector3f(offsetX, offsetY, offsetZ)

    for (cubeBlueprint in this.cubeBlueprintChildren) {
      cubeBlueprint.boneOffset = cubeOffset

      cubeBlueprint.shiftPosition()
      cubeBlueprint.shiftRotation()
    }

    cubeOffset.add(Vector3f(8.0F, 8.0F, 8.0F))

    this.boneBlueprintModelCenter = cubeOffset
  }


  private fun processBoneMap(boneMap: MutableMap<String?, Any?>) {
    setOrigin(boneMap)
    setBoneRotation(boneMap)
    if (this.isNameTag) {
      val origins = boneMap.get("origin") as MutableList<Double?>
      boneBlueprintModelCenter = Vector3f(
        origins.get(0)!!.toFloat(),
        origins.get(1)!!.toFloat() + 18,
        origins.get(2)!!.toFloat()
      )
        .mul(1 / 16f).mul(32 / 5f)
    }
  }

  private fun processChildren(
    modelName: String,
    skeletonBlueprint: SkeletonBlueprint,
    resolutionHeight: Double,
    resolutionWidth: Double,
    parsedTextureList: MutableList<ParsedTexture?>?,
    textureReferenceMap: MutableMap<String?, MutableMap<String?, Any?>?>,
    boneMap: MutableMap<String?, Any?>,
    cubeMap: HashMap<String?, Any?>,
    locatorMap: HashMap<String?, MutableMap<String?, Any?>>,
    nullObjectMap: HashMap<String?, MutableMap<String?, Any?>>
  ) {
    val childrenList = boneMap["children"] as? ArrayList<*>? ?: return

    for (`object` in childrenList) {
      if (`object` is String) {
        if (locatorMap.containsKey(`object`)) {
          val locatorData: MutableMap<String?, Any?> = locatorMap[`object`]!!

          val locatorBlueprint = LocatorBlueprint(locatorData)

          locatorBlueprint.setParentBone(this)

          skeletonBlueprint.getLocatorMap().put(`object`, locatorBlueprint)

          continue
        }

        // Check if it's a null object
        if (nullObjectMap.containsKey(`object`)) {
          val nullObjectData: MutableMap<String?, Any?> = nullObjectMap.get(`object`)!!
          val nullObjectBlueprint: NullObjectBlueprint = NullObjectBlueprint(nullObjectData)
          nullObjectBlueprint.setParentBone(this)
          skeletonBlueprint.getNullObjectMap().put(`object`, nullObjectBlueprint)
          continue
        }

        // Otherwise it's a cube
        val cubeData = cubeMap.get(`object`) as MutableMap<String?, Any?>?
        if (cubeData == null) {
          // Unknown element type, skip
          continue
        }
        val cubeBlueprint: CubeBlueprint =
          CubeBlueprint(parsedTextureList, modelName, resolutionHeight, resolutionWidth, cubeData)
        if (cubeBlueprint.isValidatedData()) cubeBlueprintChildren.add(cubeBlueprint)
        else Logger.warn("Model " + modelName + " has an invalid configuration for its cubes!")
      } else {
        //Case for object being a boneBlueprint
        val boneBlueprint = BoneBlueprint(
          modelName,
          skeletonBlueprint,
          this,
          resolutionHeight,
          resolutionWidth,
          parsedTextureList,
          textureReferenceMap,
          (`object` as kotlin.collections.MutableMap<kotlin.String?, kotlin.Any?>?)!!,
          cubeMap,
          locatorMap,
          nullObjectMap
        )
        boneBlueprintChildren.add(boneBlueprint)
        if (boneBlueprint.getMetaBone() != null) boneBlueprintChildren.add(boneBlueprint.getMetaBone())
      }
    }
  }

  private fun setBoneRotation(boneJSON: MutableMap<*, *>) {
    val boneRotation = boneJSON.get("rotation")
    if (boneRotation == null) return
    val rotations = boneRotation as MutableList<Double?>
    boneBlueprintOriginalRotation = Vector3f(
      Math.toRadians(rotations.get(0)!!).toFloat(),
      Math.toRadians(rotations.get(1)!!).toFloat(),
      Math.toRadians(rotations.get(2)!!).toFloat()
    )
  }

  private fun setOrigin(boneJSON: MutableMap<String?, Any?>) {
    val obj = boneJSON.get("origin")
    if (obj == null) return
    val origins = obj as MutableList<Double?>
    //This is the origin in "real space", meaning it is adjusted to the in-game unit size (16x larger than model space)
    boneBlueprintModelPivot = this.modelCenter.sub(
      Vector3f(
        origins.get(0)!!.toFloat(),
        origins.get(1)!!.toFloat(),
        origins.get(2)!!.toFloat()
      )
        .mul(1 / 16f)
    )
  }

  private fun generateAndWriteCubes(
    filename: String,
    textureReferences: MutableMap<String?, MutableMap<String?, Any?>?>,
    modelName: String?
  ) {
    if (filename.equals("hitbox", ignoreCase = true) || filename.equals(
        "tag_name",
        ignoreCase = true
      ) || cubeBlueprintChildren.isEmpty()
    ) return
    val textureReferencesClone: MutableMap<String?, Any?> = HashMap<String?, Any?>(textureReferences)
    setDisplay(textureReferencesClone)
    writeCubes(textureReferencesClone)
    writeFile(modelName, filename, textureReferencesClone)
  }

  private fun getModelDirectory(modelName: String?): String {
    return MetadataHandler.PLUGIN.getDataFolder()
      .getAbsolutePath() + File.separatorChar + "output" + File.separatorChar + "FreeMinecraftModels" + File.separatorChar + "assets" + File.separatorChar + "freeminecraftmodels" + File.separatorChar + "models" + File.separatorChar + modelName
  }

  private fun writeCubes(textureReferencesClone: MutableMap<String?, Any?>) {
    val cubeJSONs: MutableList<Any?> = ArrayList<Any?>()

    //This generates the JSON for each individual cubes
    for (cubeBlueprint in cubeBlueprintChildren) cubeJSONs.add(cubeBlueprint.getCubeJSON())

    textureReferencesClone.put("elements", cubeJSONs)
  }

  /**
   * Centers the model in the armor stand
   * 
   * @param textureReferencesClone Map to modify
   */
  private fun setDisplay(textureReferencesClone: MutableMap<String?, Any?>) {
    textureReferencesClone.put(
      "display", Map.of(
        "head", Map.of(
          "translation", List.of(
            0,
            -6.4,
            0
          ),
          "scale", List.of<Float?>(MODEL_SCALE, MODEL_SCALE, MODEL_SCALE)
        )
      )
    )
  }

  private fun writeFile(modelName: String?, filename: String?, boneJSON: MutableMap<String?, Any?>?) {
    val modelDirectory = getModelDirectory(modelName)
    val gson = Gson()
    try {
      FileUtils.writeStringToFile(
        File(modelDirectory + File.separatorChar + filename + ".json").also { file = it },
        gson.toJson(boneJSON),
        StandardCharsets.UTF_8
      )
    } catch (e: Exception) {
      Logger.warn("Failed to write boneBlueprint resource packs for boneBlueprint " + filename + "!")
      throw RuntimeException(e)
    }
  }

  companion object {
    //This multiplier converts units from the bbmodel units to the resource pack units, needed because the model is scaled up
    // by 4x to bypass the Minecraft limitations and
    const val ARMOR_STAND_HEAD_SIZE_MULTIPLIER: Float = 0.4f

    //This sets the scale of the model for the resource pack
    private const val MODEL_SCALE = 4f

    @Getter
    private const val ARMOR_STAND_PIVOT_POINT_HEIGHT = 1.438f

    //This multiplier converts resource pack units back to bbmodel units
    @JvmField
    var nameTagKey: NamespacedKey = NamespacedKey(MetadataHandler.PLUGIN, "NameTag")
  }
}
