package com.unityrealms.server.modelengine.model.skeleton.bone

import com.google.gson.Gson
import com.unityrealms.server.modelengine.model.cube.CubeBlueprint
import org.joml.Vector3f

import java.io.File
import java.nio.charset.StandardCharsets

import kotlin.math.abs

class BoneBlueprint {

  private val cubeBlueprintChildren: MutableList<CubeBlueprint> = ArrayList<CubeBlueprint>()


  private val boneName: String

  private val originalModelName: String?

  private val originalBoneName: String

  private val uuid: String?

  private val boneBlueprintChildren: MutableList<BoneBlueprint?> = ArrayList<BoneBlueprint?>()

  private val modelID: String? = null

  private var nameTag = false

  private var parent: BoneBlueprint? = null
  private var isDisplayModel = true

  //Actual center of the model in the model space
  private var blueprintModelCenter: Vector3f = Vector3f()

  //Pivot point relative to the model center
  private var blueprintModelPivot: Vector3f? = null
  private var blueprintOriginalBoneRotation: Vector3f = Vector3f()

  private var isHead = false

  private var mountPoint = false

  /**
   * This is a bit of a cursed solution, but there's not that many ways around it.
   * The purpose of this bone is to create a parallel bone for meta bones without interfering with the structural bones.
   * Specifically, right now, the meta bone is used for nametags which benefit from having some special properties which would break structural bones.
   */
  @Getter
  private var metaBone: BoneBlueprint? = null


  @Getter
  private var file: File? = null

  /**
   * This is for the empty root bone only
   * 
   * @param modelName
   * @param parent
   * @param skeletonBlueprint
   */
  constructor(modelName: String, parent: BoneBlueprint?, skeletonBlueprint: SkeletonBlueprint) {
    this.originalBoneName = "freeminecraftmodels_autogenerated_root"
    this.boneName = "freeminecraftmodels:" + modelName + "/" + StringToResourcePackFilename.convert(originalBoneName)
    this.originalModelName = modelName
    this.parent = parent
    this.uuid = null // Auto-generated root bone has no UUID
    //Add bone to the map
    skeletonBlueprint.getBoneMap().put(originalBoneName, this)
    blueprintModelPivot = Vector3f()
    blueprintOriginalBoneRotation = Vector3f()
  }

  /**
   * This is for the actual values
   * 
   * @param parsedTextures    List of parsed textures
   * @param boneJSON          The bone data from the bbmodel file
   * @param values            Map of cube UUIDs to cube data
   * @param locators          Map of locator UUIDs to locator data
   * @param nullObjects       Map of null object UUIDs to null object data
   * @param textureReferences Texture references for resource pack
   * @param modelName         Name of the model
   * @param parent            Parent bone
   * @param skeletonBlueprint The skeleton blueprint
   * @param resolutionWidth   Texture resolution width
   * @param resolutionHeight  Texture resolution height
   */
  constructor(
    parsedTextures: MutableList<ParsedTexture?>?, boneJSON: MutableMap<String?, Any?>, values: HashMap<String?, Any?>,
    locators: HashMap<String?, MutableMap<String?, Any?>>, nullObjects: HashMap<String?, MutableMap<String?, Any?>>,
    textureReferences: MutableMap<String?, MutableMap<String?, Any?>?>, modelName: String, parent: BoneBlueprint?,
    skeletonBlueprint: SkeletonBlueprint, resolutionWidth: Double, resolutionHeight: Double
  ) {
    this.originalBoneName = boneJSON.get("name") as String
    this.boneName = "freeminecraftmodels:" + modelName + "/" + StringToResourcePackFilename.convert(originalBoneName)
    this.originalModelName = modelName
    this.parent = parent
    this.uuid = boneJSON.get("uuid") as String?
    if (originalBoneName.startsWith("tag_")) {
      metaBone = BoneBlueprint(boneJSON, modelName, parent, skeletonBlueprint)
    }
    //Some bones should not be displayed because they just hold metadata
    if (originalBoneName.startsWith("b_") || originalBoneName.equals("hitbox", ignoreCase = true)) isDisplayModel =
      false
    if (originalBoneName.startsWith("h_")) isHead = true
    if (originalBoneName.startsWith("mount_")) mountPoint = true

    //Add bone to the map
    skeletonBlueprint.getBoneMap().put(originalBoneName, this)
    //Also add by UUID for IK chain lookup
    if (uuid != null) {
      skeletonBlueprint.getBoneByUuidMap().put(uuid, this)
    }

    //Initialize child data
    processChildren(
      parsedTextures,
      boneJSON,
      modelName,
      values,
      locators,
      nullObjects,
      textureReferences,
      skeletonBlueprint,
      resolutionWidth,
      resolutionHeight
    )
    adjustCubes()
    processBoneValues(boneJSON)
    val filename: String = StringToResourcePackFilename.convert(originalBoneName)
    generateAndWriteCubes(filename, textureReferences, modelName)
  }

  constructor(
    boneJSON: MutableMap<String?, Any?>,
    modelName: String,
    parent: BoneBlueprint?,
    skeletonBlueprint: SkeletonBlueprint
  ) {
    this.originalBoneName = "fmm_nametag_bone_" + boneJSON.get("name")
    this.boneName = "freeminecraftmodels:" + modelName + "/" + StringToResourcePackFilename.convert(originalBoneName)
    this.originalModelName = modelName
    this.parent = parent
    this.uuid = null // Auto-generated nametag bone has no UUID
    nameTag = true

    //Add bone to the map
    skeletonBlueprint.getBoneMap().put(originalBoneName, this)

    //Simple center of the bone
    processBoneValues(boneJSON)
  }

  fun getBlueprintOriginalBoneRotation(): Vector3f {
    return Vector3f(blueprintOriginalBoneRotation)
  }

  fun isDisplayModel(): Boolean {
    return isDisplayModel && (modelID != null || nameTag)
  }

  val modelCenter: Vector3f
    //move to real space
    get() {
      val rpToBlocks = 1f / 16f
      val unscale: Float = 1f / ARMOR_STAND_HEAD_SIZE_MULTIPLIER
      return Vector3f(blueprintModelCenter).mul(rpToBlocks * unscale)
    }

  fun getBlueprintModelPivot(): Vector3f {
    return Vector3f(blueprintModelPivot)
  }

  private fun adjustCubes() {
    if (cubeBlueprintChildren.isEmpty()) return
    //Get the lowest and highest coordinates of the cube, shifted by the origin, adjusted by the scaling of the resource pack to fit the rest of the cube data
    var lowestX: Float? = null
    var lowestY: Float? = null
    var lowestZ: Float? = null
    var highestX: Float? = null
    var highestY: Float? = null
    var highestZ: Float? = null
    for (cubeBlueprint in cubeBlueprintChildren) {
      if (lowestX == null || cubeBlueprint..get(0) < lowestX) lowestX = cubeBlueprint.getFrom().get(0)
      if (lowestY == null || cubeBlueprint.getFrom().get(1) < lowestY) lowestY = cubeBlueprint.getFrom().get(1)
      if (lowestZ == null || cubeBlueprint.getFrom().get(2) < lowestZ) lowestZ = cubeBlueprint.getFrom().get(2)
      if (highestX == null || cubeBlueprint.getTo().get(0) > highestX) highestX = cubeBlueprint.getTo().get(0)
      if (highestY == null || cubeBlueprint.getTo().get(1) > highestY) highestY = cubeBlueprint.getTo().get(1)
      if (highestZ == null || cubeBlueprint.getTo().get(2) > highestZ) highestZ = cubeBlueprint.getTo().get(2)
    }

    //Get the size of the entire bone (not necessarily just one cube), in the scaled down version
    val xSize = abs(highestX!! - lowestX!!)
    val ySize = abs(highestY!! - lowestY!!)
    val zSize = abs(highestZ!! - lowestZ!!)

    //If the bone exceeds (16+32)*4 in size (remember, this is scaled) then it is too large to be rendered
    //This is because the lowest value is -16, the highest is +32 and the model is scaled up by 4x
    if (xSize > 48 * MODEL_SCALE || ySize > 48 * MODEL_SCALE || zSize > 48 * MODEL_SCALE) {
      Logger.warn("Model " + originalModelName + " has a boneBlueprint or set of cubes which exceeds the maximum size! Either make the cubes smaller, less far apart or split them up into multiple bones!")
    }

    //Find new lowest point in the cube, and shift it by the amount of the origin - currently in normal resource pack units
    //Note: 8 is the midpoint between -16 and +32, which are the limits for a resource pack
    //Important: this is normal resource pack units, not scaled down units
    val newLowestX = 8 - xSize / 2f
    val newLowestY = 8 - ySize / 2f
    val newLowestZ = 8 - zSize / 2f

    //The difference between the lowest point - in normal resource pack units
    val xOffset = lowestX - newLowestX
    val yOffset = lowestY - newLowestY
    val zOffset = lowestZ - newLowestZ

    //Get offset based on the cube shift, this is technically in normal resource pack units as the shifts need to be done in that unit size
    val cubeOffset: Vector3f = Vector3f(xOffset, yOffset, zOffset)

    //Uniformly shift the cubes and finalize writing their JSON data
    for (cubeBlueprint in cubeBlueprintChildren) {
      cubeBlueprint.setBoneOffset(cubeOffset)
      cubeBlueprint.shiftPosition()
      cubeBlueprint.shiftRotation()
    }

    //This should shift the origin so it is adequately centered on 8,8,8
    cubeOffset.add(Vector3f(8f, 8f, 8f))

    //This is actually how much the center of the blocks has shifted from 0,0,0 in the model space
    blueprintModelCenter = cubeOffset
  }

  private fun processBoneValues(boneJSON: MutableMap<String?, Any?>) {
    setOrigin(boneJSON)
    setBoneRotation(boneJSON)
    if (isNameTag()) {
      val origins = boneJSON.get("origin") as MutableList<Double?>
      blueprintModelCenter = Vector3f(
        origins.get(0)!!.toFloat(),
        origins.get(1)!!.toFloat() + 18,
        origins.get(2)!!.toFloat()
      )
        .mul(1 / 16f).mul(32 / 5f)
    }
  }

  private fun processChildren(
    parsedTextures: MutableList<ParsedTexture?>?,
    boneJSON: MutableMap<String?, Any?>,
    modelName: String,
    values: HashMap<String?, Any?>,
    locators: HashMap<String?, MutableMap<String?, Any?>>,
    nullObjects: HashMap<String?, MutableMap<String?, Any?>>,
    textureReferences: MutableMap<String?, MutableMap<String?, Any?>?>,
    skeletonBlueprint: SkeletonBlueprint,
    resolutionWidth: Double,
    resolutionHeight: Double
  ) {
    //Bones can contain children: bones, cubes, locators, and null objects
    //Bones exist solely for containing cubes
    //Cubes store the relevant visual data
    //Locators are anchor points for IK
    //Null objects are IK controllers
    val childrenValues = boneJSON.get("children") as ArrayList<*>?
    if (childrenValues == null) return

    for (`object` in childrenValues) {
      if (`object` is String) {
        val childUUID = `object`

        // Check if it's a locator
        if (locators.containsKey(childUUID)) {
          val locatorData: MutableMap<String?, Any?> = locators.get(childUUID)!!
          val locatorBlueprint: LocatorBlueprint = LocatorBlueprint(locatorData)
          locatorBlueprint.setParentBone(this)
          skeletonBlueprint.getLocatorMap().put(childUUID, locatorBlueprint)
          continue
        }

        // Check if it's a null object
        if (nullObjects.containsKey(childUUID)) {
          val nullObjectData: MutableMap<String?, Any?> = nullObjects.get(childUUID)!!
          val nullObjectBlueprint: NullObjectBlueprint = NullObjectBlueprint(nullObjectData)
          nullObjectBlueprint.setParentBone(this)
          skeletonBlueprint.getNullObjectMap().put(childUUID, nullObjectBlueprint)
          continue
        }

        // Otherwise it's a cube
        val cubeData = values.get(childUUID) as MutableMap<String?, Any?>?
        if (cubeData == null) {
          // Unknown element type, skip
          continue
        }
        val cubeBlueprint: CubeBlueprint =
          CubeBlueprint(parsedTextures, modelName, resolutionHeight, resolutionWidth, cubeData)
        if (cubeBlueprint.isValidatedData()) cubeBlueprintChildren.add(cubeBlueprint)
        else Logger.warn("Model " + modelName + " has an invalid configuration for its cubes!")
      } else {
        //Case for object being a boneBlueprint
        val boneBlueprint = BoneBlueprint(
          parsedTextures,
          (`object` as kotlin.collections.MutableMap<kotlin.String?, kotlin.Any?>?)!!,
          values,
          locators,
          nullObjects,
          textureReferences,
          modelName,
          this,
          skeletonBlueprint,
          resolutionWidth,
          resolutionHeight
        )
        boneBlueprintChildren.add(boneBlueprint)
        if (boneBlueprint.getMetaBone() != null) boneBlueprintChildren.add(boneBlueprint.getMetaBone())
      }
    }
  }

  private fun setBoneRotation(boneJSON: MutableMap<*, *>) {
    val boneRotation = boneJSON.get("rotation")
    if (boneRotation == null) return
    val rotations = boneRotation as MutableList<Double?>
    blueprintOriginalBoneRotation = Vector3f(
      Math.toRadians(rotations.get(0)!!).toFloat(),
      Math.toRadians(rotations.get(1)!!).toFloat(),
      Math.toRadians(rotations.get(2)!!).toFloat()
    )
  }

  private fun setOrigin(boneJSON: MutableMap<String?, Any?>) {
    val obj = boneJSON.get("origin")
    if (obj == null) return
    val origins = obj as MutableList<Double?>
    //This is the origin in "real space", meaning it is adjusted to the in-game unit size (16x larger than model space)
    blueprintModelPivot = this.modelCenter.sub(
      Vector3f(
        origins.get(0)!!.toFloat(),
        origins.get(1)!!.toFloat(),
        origins.get(2)!!.toFloat()
      )
        .mul(1 / 16f)
    )
  }

  private fun generateAndWriteCubes(
    filename: String,
    textureReferences: MutableMap<String?, MutableMap<String?, Any?>?>,
    modelName: String?
  ) {
    if (filename.equals("hitbox", ignoreCase = true) || filename.equals(
        "tag_name",
        ignoreCase = true
      ) || cubeBlueprintChildren.isEmpty()
    ) return
    val textureReferencesClone: MutableMap<String?, Any?> = HashMap<String?, Any?>(textureReferences)
    setDisplay(textureReferencesClone)
    writeCubes(textureReferencesClone)
    writeFile(modelName, filename, textureReferencesClone)
  }

  private fun getModelDirectory(modelName: String?): String {
    return MetadataHandler.PLUGIN.getDataFolder()
      .getAbsolutePath() + File.separatorChar + "output" + File.separatorChar + "FreeMinecraftModels" + File.separatorChar + "assets" + File.separatorChar + "freeminecraftmodels" + File.separatorChar + "models" + File.separatorChar + modelName
  }

  private fun writeCubes(textureReferencesClone: MutableMap<String?, Any?>) {
    val cubeJSONs: MutableList<Any?> = ArrayList<Any?>()

    //This generates the JSON for each individual cubes
    for (cubeBlueprint in cubeBlueprintChildren) cubeJSONs.add(cubeBlueprint.getCubeJSON())

    textureReferencesClone.put("elements", cubeJSONs)
  }

  /**
   * Centers the model in the armor stand
   * 
   * @param textureReferencesClone Map to modify
   */
  private fun setDisplay(textureReferencesClone: MutableMap<String?, Any?>) {
    textureReferencesClone.put(
      "display", Map.of(
        "head", Map.of(
          "translation", List.of(
            0,
            -6.4,
            0
          ),
          "scale", List.of<Float?>(MODEL_SCALE, MODEL_SCALE, MODEL_SCALE)
        )
      )
    )
  }

  private fun writeFile(modelName: String?, filename: String?, boneJSON: MutableMap<String?, Any?>?) {
    val modelDirectory = getModelDirectory(modelName)
    val gson = Gson()
    try {
      FileUtils.writeStringToFile(
        File(modelDirectory + File.separatorChar + filename + ".json").also { file = it },
        gson.toJson(boneJSON),
        StandardCharsets.UTF_8
      )
    } catch (e: Exception) {
      Logger.warn("Failed to write boneBlueprint resource packs for boneBlueprint " + filename + "!")
      throw RuntimeException(e)
    }
  }

  companion object {
    //This multiplier converts units from the bbmodel units to the resource pack units, needed because the model is scaled up
    // by 4x to bypass the Minecraft limitations and
    const val ARMOR_STAND_HEAD_SIZE_MULTIPLIER: Float = 0.4f

    //This sets the scale of the model for the resource pack
    private const val MODEL_SCALE = 4f

    @Getter
    private const val ARMOR_STAND_PIVOT_POINT_HEIGHT = 1.438f

    //This multiplier converts resource pack units back to bbmodel units
    @JvmField
    var nameTagKey: NamespacedKey = NamespacedKey(MetadataHandler.PLUGIN, "NameTag")
  }
}
